### ISSUE TITLE
UA silence

### ISSUE THREAD

**Issue by lwznrx** [wotlk-addons/LoseControl#2]
https://github.com/vendethiel/wotlk-losecontrol/blob/master/LoseControl.lua#L427
name, rank, icon, count, debuffType, duration, expirationTime, unitCaster, isStealable, nameplateShowPersonal, spellId, canApplyAura, isBossDebuff, nameplateShowAll, timeMod, value1, value2, value3
Utiliser le spellID, ne pas prendre en compte la ligne si elle contient le spellID de l'UA debuff (éventuellement gérer chaque rank de l'UA, au pire juste max rank)

**Comment by vendethiel** [comment]
Closable?

**Comment by lwznrx** [comment]
yes
